### ISSUE TITLE
How to use global keyboard shortcuts?

### ISSUE THREAD

**Issue by themaclanky** [Longoon12000/VoxYou#16]
Hello, just wanted to say that this software works great!!

I'm a little confused, though: 1.0.12 says it has support for global keyboard shortcuts, but i can't find them anywhere. Also, is it possible to control the vst's with them? Thanks in advance.

**Comment by RainOrigami** [comment]
Hello @themaclanky 

in the MIDI to VST FX window (MIDI Device -> MIDI Mapping) you can press a key combination (a modifier plus a button) to create a global MIDI trigger that can be used to control VST plugins.

![image](https://user-images.githubusercontent.com/51454971/83747419-e1960d00-a660-11ea-8815-c3c3c4b9a5de.png)

Hope this helps, let me know if you have any further questions!

**Comment by themaclanky** [comment]
Ohh... ok!!
It works perfectly, thanks for the help 👍
